spring.application.name=backend
server.port=8080
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://10.72.4.135:5432/itiap
=======
spring.datasource.url=jdbc:postgresql://10.72.4.135/itiap
>>>>>>> 172d9c987605bb9ac01b7a007573d93e9b1d32d8
spring.datasource.username=postgres
spring.datasource.password=mKnic123
spring.datasource.driver-class-name=org.postgresql.Driver