spring.application.name=backend
server.port=8080
spring.datasource.url=jdbc:postgresql://10.72.4.135/itiap
spring.datasource.username=postgres
spring.datasource.password=mknic123
spring.datasource.driver-class-name=org.postgresql.Driver